name: docker-clickhouse
on: 
  workflow_dispatch: 
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: install_test
        run: |
          apt-get insatll -y wget curl git
          curl -fsSL https://get.docker.com -o get-docker.sh|/bin/bash
          service docker start 
          docker ps 
          docker pull ubuntu
          docker tag ubuntu:latest mymessagebox/clickhouse:ubuntu 
          docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_PASSWORD }}
          docker push mymessagebox/clickhouse:ubuntu 
